version: "3.9"
services:
  web:
    build: Capstone-React
    ports:
      - "3000:3000"
  spring:
    build: Capstone-Spring
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_PASSWORD: password
      project.frontend.url: http://web:3000

    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    # expose:
    #   - 5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
