
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: '14'

      - name: clone repo
        run: git clone https://github.com/LionelBeato/Capstone-React.git
    
      - name: Build frontend
        working-directory: Capstone-React
        run: |
         npm install
         npm run build

        
      #  npm run build
      #  cp build ../Capstone-Spring/src/main/resources/static
      #  cd ../Capstone-Spring/src/main/resources/static 
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
