
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Build frontend
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: | 
          npm run build
          ls
      #  npm run build
      #  cp build ../Capstone-Spring/src/main/resources/static
      #  cd ../Capstone-Spring/src/main/resources/static 
        working-directory: Capstone-React

        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
