
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: clone repo
        run: git clone https://github.com/LionelBeato/Capstone-React.git
    
      - name: Build frontend
        working-directory: Capstone-React
        env:
          CI: ""
        run: |
         npm install
         npm run build
         
#       - name: Copy Directory
#         uses: MadaraUchiha/copy-action@0.0.1
#         with:
#          source: "Capstone-React/build"
#          target: "Capstone-Spring/src/main/resources/static"

      - name: copy directory
        run: |
          cp -r Capstone-React/build ./
          ls
          mv build Capstone-Spring
          ls
      
      
         
         
 
         

